version: "3.8"
services:
  mongodb:
    image: "mongo"
    container_name: "mongodb"
    volumes:
      - data:/data/db
    env_file:
      - ./env/mongo.env
    # environment:
    #     # MONGO_INITDB_ROOT_USERNAME: max
    #     # MONGO_INITDB_ROOT_PASSWORD: secret

  backend:
    build: ./backend
    container_name: "bcakend-app"
    ports:
      - "80:80"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file: ./env/backend.env
    depends_on:
      - mongodb

volumes:
  data:
  logs:
