version: "3.8"
services:
  mongodb:
    image: "mongo"
    container_name: "mongodb"
    volumes:
      - data:/data/db
    env_file:
      - ./env/mongo.env
    # environment:
    #     # MONGO_INITDB_ROOT_USERNAME: max
    #     # MONGO_INITDB_ROOT_PASSWORD: secret
volumes:
  data:
